/**
 * Article Actions
 * @type {string}
 */
export const GET_ARTICLES = 'GET_ARTICLES';


/**
 * Candidate Actions
 * @type {string}
 */
export const BEGIN_GET_CANDIDATE = 'BEGIN_GET_CANDIDATE';
export const GET_CANDIDATE_SUCCESS = ' GET_CANDIDATE_SUCCESS';
export const GET_CANDIDATE_FAILURE = ' GET_CANDIDATE_FAILURE';
export const GET_CANDIDATE_RESUME_SUCCESS = 'GET_CANDIDATE_RESUME_SUCCESS';

export const CANDIDATE_SAVE_SUCCESS = 'CANDIDATE_SAVE_SUCCESS';
export const CANDIDATE_SAVE_FAILURE = 'CANDIDATE_SAVE_FAILURE';
export const CANDIDATE_SAVE_BEGIN = 'CANDIDATE_SAVE_BEGIN';


export const BEGIN_GET_CANDIDATE_APPLIED_POSITION_STATUS = 'BEGIN_GET_CANDIDATE_APPLIED_POSITION_STATUS';
export const GET_CANDIDATE_SUCCESS_APPLIED_POSITION_STATUS = ' GET_CANDIDATE_SUCCESS_APPLIED_POSITION_STATUS';
export const GET_CANDIDATE_FAILURE_APPLIED_POSITION_STATUS = ' GET_CANDIDATE_FAILURE_APPLIED_POSITION_STATUS';

export const SET_CANDIDATE_FORM_CHANGE = 'SET_CANDIDATE_FORM_CHANGE';

/**
 * Vacancy Actions
 * @type {string}
 */
export const BEGIN_GET_POSITION = 'BEGIN_GET_POSITION';
export const GET_POSITION_SUCCESS = 'GET_POSITION_SUCCESS';
export const GET_POSITION_FAILURE = 'GET_POSITION_FAILURE';


export const BEGIN_GET_ACTIVE_POSITION = 'BEGIN_GET_ACTIVE_POSITION';
export const GET_ACTIVE__POSITION_SUCCESS = 'GET_ACTIVE__POSITION_SUCCESS';
export const GET_ACTIVE_POSITION_FAILURE = 'GET_ACTIVE_POSITION_FAILURE';

export const BEGIN_POST_POSITION = 'BEGIN_POST_POSITION';
export const POST_POSITION_SUCCESS = 'POST_POSITION_SUCCESS';
export const POST_POSITION_FAILURE = 'POST_POSITION_FAILURE';



/**
 * QUALIFICATION Actions
 * @type {string}
 */
export const BEGIN_GET_QUALIFICATION = 'BEGIN_GET_QUALIFICATION';
export const GET_QUALIFICATION_SUCCESS = 'GET_QUALIFICATION_SUCCESS';
export const GET_QUALIFICATION_FAILURE = 'GET_QUALIFICATION_FAILURE';



/**
 * User Actions
 * @type {string}
 */
export const BEGIN_GET_CURRENT_USER = 'BEGIN_GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER';


export const BEGIN_LOGGING_IN = 'BEGIN_LOGGING_IN';
export const LOGGING_IN_SUCCESS = 'LOGGING_IN_SUCCESS';
export const LOGGING_IN_FAILURE = 'LOGGING_IN_FAILURE';


